services:
  backend:
    build: 
      context: ../backend
      dockerfile: ./docker/Dockerfile.dev
    image: unrealducks-backend-dev
    container_name: unrealducks-backend-dev
    stdin_open: true
    tty: true
    volumes:
      - ../backend/src:/app/src
      - ../backend/build:/app/build
      - ../backend/settings.gradle:/app/settings.gradle
      - ../backend/build.gradle:/app/build.gradle
    networks:
      - unrealducks-network
    ports:
      - "8080:8080"
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    restart: always

networks:
  unrealducks-network:
    driver: bridge