services:
  backend:
    build: 
      context: ../backend
      dockerfile: ./docker/Dockerfile.prod
    image: unrealducks-backend-prod
    container_name: unrealducks-backend-prod
    ports:
      - "8080:8080"
    restart: always