services:
  backend:
    build: 
      context: ../backend
      dockerfile: ./docker/Dockerfile.prod
    image: unrealducks-backend-prod
    container_name: unrealducks-backend-prod
    networks:
      - unrealducks-network
    ports:
      - "8080:8080"
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    restart: always

networks:
  unrealducks-network:
    external: true