version: '3.9'

services:
  database:
    image: postgres:13.18
    container_name: unrealducks-database
    volumes:
      - ../database:/var/lib/postgresql/data
    networks:
      - unrealducks-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_DB}
    restart: always

networks:
  unrealducks-network:
    driver: bridge

volumes:
  postgres_data:
