services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: unrealducks-jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ../jenkins:/var/jenkins_home
    restart: always
    networks:
      - unrealducks-network

networks:
  unrealducks-network:
    driver: bridge
