services:
  jenkins:
    image: jenkins/jenkins:alpine-jdk21
    container_name: unrealducks-jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ../jenkins:/var/jenkins_home
    restart: always

networks:
  unrealducks-network:
    driver: bridge
