version: '3.9'

services:
  postgres:
    image: postgres:14.15-alpine
    container_name: unrealducks-postgres
    volumes:
      - ../postgres:/var/lib/postgresql/data
    networks:
      - unrealducks-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_DB}
    restart: always

networks:
  unrealducks-network:
    driver: bridge
