services:
  sonar-postgres:
    image: postgres:14.15-alpine
    container_name: unrealducks-sonar-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: sonarqube
    volumes:
      - ../sonarqube/postgres:/var/lib/postgresql/data
    networks:
      - unrealducks-sonar-network

  sonar-sonarqube:
    image: sonarqube:lts-community
    container_name: unrealducks-sonar-sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: ${DATABASE_USER}
      SONAR_JDBC_PASSWORD: ${DATABASE_PASS}
    ports:
      - "9000:9000"
    volumes:
      - ../sonarqube/sonarqube/data:/opt/sonarqube/data
      - ../sonarqube/sonarqube/extensions:/opt/sonarqube/extensions
      - ../sonarqube/sonarqube/logs:/opt/sonarqube/logs
    depends_on:
      - sonar-postgres
    networks:
      - unrealducks-sonar-network

networks:
  unrealducks-sonar-network:
    driver: bridge
