services:
  sonar-sonar-scanner:
    image: sonarsource/sonar-scanner-cli:11.1
    container_name: unrealducks-sonar-sonar-scanner
    environment:
      SONAR_HOST_URL: "http://sonar-sonarqube:9000"
      SONAR_TOKEN: ${SONAR_TOKEN}
    working_dir: /tmp/backend
    volumes:
      - ../backend/src:/tmp/backend/src
      - ../backend/build/classes:/tmp/backend/build/classes
      - ../backend/sonar-project.properties:/tmp/backend/sonar-project.properties
      - ../backend/.scannerwork:/tmp/backend/.scannerwork
    networks:
      - unrealducks-sonar-network
    entrypoint: ["/bin/sh", "-c", "sonar-scanner -Dsonar.login=${SONAR_TOKEN} -X"]

networks:
  unrealducks-sonar-network:
    driver: bridge